#### Script to generate species richness map ####
## uses output generated by code/01_creating_hex_richness.R

# loading packages
library("ggplot2")

# loading table
hex_rich <- read.csv('results/hex_richness.csv')

head(hex_rich)

pal <- wesanderson::wes_palette("Zissou1", 100, type = "continuous")

map <- ggplot(hex_rich) +
  aes(long, lat, group = group, fill = N) +
  theme_void() +
  scale_fill_gradientn(colours = c("grey", pal)) +
  geom_polygon() +
  geom_path(color = "white") +
  coord_equal() +
  labs(title = "Brazilian endangered plant species",
       fill = "Richness") +
  theme(#legend.position = "bottom",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10),
        legend.key.size = unit(0.4, "cm"))


png("figs/map_richness_hex.png", res = 300,
    height = 1200, width = 1200)
map
dev.off()
